package dev.shushant.permissionframework.permissions

import dev.shushant.sun_and_storm_kmp.permissions.ios.PermissionsControllerProtocol

actual typealias PermissionsController = PermissionsControllerProtocol
